### ISSUE TITLE
Skipping stashes with NULL accountNames creates "ghost" items

### ISSUE THREAD

**Issue by Superchicken** [licoffe/POE-Stash-indexer-NG#12]
When processing json, stashes with a NULL accountName are skipped [(here)](https://github.com/licoffe/POE-Stash-indexer-NG/blob/94d57fe9930e05036f8f6050ee2d849417698d42/main.cpp#L708-L715). 

        // If there is a valid accountName value
        if ( array.HasMember( "accountName" ) && !array["accountName"].IsNull()) {
            assert(array["accountName"].IsString());
            account_name = array["accountName"].GetString();
        } else {
            // If not, skip this stash tab
            continue;
        }

A NULL accountName indicates that the stash no longer exists/is removed, as Novynn mentioned here: https://www.reddit.com/r/pathofexiledev/comments/54b20b/empty_accountcharacter_names/

If I'm interpreting correctly, the relevant stash+item records should be removed from the database, because the items in that tab should also no longer exist.

**Comment by licoffe** [comment]
Hi Deepak, you're definitely right :) Thank you for reporting! I'll post a patch to fix this soon.

**Comment by licoffe** [comment]
Just published a patch to remove **Items** and **Stashes** entries for which the **stashId** is linked to an empty account name.
