### ISSUE TITLE
Searching for an item with foil version only displays the data for the foil version

### ISSUE THREAD

**Issue by superouman** [licoffe/POE-Stash-indexer-NG#13]
Lightning coil : http://poe-rates.com/index.php?league=Legacy&item=Lightning%20Coil&interval=1h
Windripper : http://poe-rates.com/index.php?league=Legacy&item=Windripper&interval=7d
Voidheart : http://poe-rates.com/index.php?league=Legacy&item=Voidheart&interval=7d

Shavronne Wrappings display the stats for 6Link normal version in addition to the foil version data : http://poe-rates.com/index.php?league=Legacy&item=Shavronne%27s%20Wrappings&interval=7d

**Comment by licoffe** [comment]
Yeah, just noticed as well. I'm working on a fix. Thanks for reporting!

**Comment by licoffe** [comment]
Deploying a fix, let's see if it works.

**Comment by licoffe** [comment]
Fixed!
