### ISSUE TITLE
poe-rates.com

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-Stash-indexer-NG#22]
Hi Licoffe,

Quick question.  Is there a way to save my searches on poe-rates.com/live?  What I mean is, if I were to clear my cache, browser history, etc I would have to recreate everything from scratch.  Is there a way to export the searches I have built so far so that I wouldn't lose them in that case?

Thanks,
Tim

**Comment by gdneye** [comment]
Nevermind.  I found it.  Thanks!

**Comment by gdneye** [comment]
Sorry, I think I'm going too fast.  It looks like the export function I found is only for the configuration?

**Comment by licoffe** [comment]
Hi Gdneye,

The export function currently exports your settings as well as all your filters. I will update the tool to make this more explicit :)

Best

**Comment by gdneye** [comment]
oh cool, thanks!
