### ISSUE TITLE
Data truncated for column 'modValue1'

### ISSUE THREAD

**Issue by Superchicken** [licoffe/POE-Stash-indexer-NG#3]
Running on Ubuntu 16.10 mysql 5.7.

I'm receiving error: 

> ERR: SQLException in main.cpp
>(print_sql_error) on line 215
> ERR: Data truncated for column 'modValue1' at row 19
> (MySQL error code: 1265
>, SQLState: 01000 )
>LOAD DATA CONCURRENT INFILE 'mods_0.txt' REPLACE INTO TABLE `Mods` FIELDS TERMINATED BY ',' >ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
>'

Looking at the line causing the error, I notice it is the first line to have no value specified for modValue1:

> "5e968f419af74b6c673927fd0f083ab3599573d2879d1f6e9c27085a761ea9fa","Immune to Curses during Flask effect;Removes Curses on use","","","","","EXPLICIT","5e968f419af74b6c673927fd0f083ab3599573d2879d1f6e9c27085a761ea9fa2"

Manually editing in a "0" for modValue1 and manually executing the SQL query resolves the error for that line, but pushes the error to the next instance of a blank valued modValue1.

It seems like LOAD DATA INFILE isn't handling empty values correctly, [source](http://stackoverflow.com/questions/15169788/getting-a-mysql-error-code-1265-data-truncated-for-column-when-doing-a-load-da)

**Comment by Superchicken** [comment]
My current workaround is changing the SQL query on line 1316 in [main.cpp](https://github.com/licoffe/POE-Stash-indexer-NG/blob/master/main.cpp#L1316)

> threaded_insert( "LOAD DATA CONCURRENT INFILE '" + mod_file + "' REPLACE INTO TABLE `Mods` FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"' LINES TERMINATED BY '\n' **(itemId, modName, @vmodValue1, modValue2, modValue3, modValue4, modType, modKey) set modValue1 = nullif(@vmodValue1, '')**" );

Where my additions are in bold. I'm not sure how much this will affect performance or if it's a suitable solution.

**Comment by licoffe** [comment]
I modified the schema.sql, it seems to fix the issue. Could you try importing it and run the indexer again?

**Comment by Superchicken** [comment]
Thanks, your changes have resolved this issue.

**Comment by licoffe** [comment]
Sure, glad it helped :)
