### ISSUE TITLE
modName Column undersized

### ISSUE THREAD

**Issue by Superchicken** [licoffe/POE-Stash-indexer-NG#4]
The modName column in the Mods table is too short, it is [currently varchar(128)](https://github.com/licoffe/POE-Stash-indexer-NG/blob/master/schema.sql#L133).

This mod is over 128 characters (147?) and I don't know if it is even the longest mod name.

> With at least # Intelligence Allocated in Radius, Fireball Projectiles gain Area of Effect Radius as they travel farther, up to #% increased Radius

SQL errors when trying to insert this because it is too long, I have changed my local table to varchar(256) for now with:

> alter table Mods change column modName modName VARCHAR(256);

**Comment by licoffe** [comment]
I don't have these errors on my Debian install for some reasons. I set the modName length to 1024 to be on the safe side in the last commit.

**Comment by Superchicken** [comment]
Thanks for the quick response, using modName length 1024 passes the max size allowed on my install when importing schema.sql (ubuntu 16.10 sql 5.7 default settings)

> ERROR 1071 (42000) at line 131: Specified key was too long; max key length is 3072 bytes

Instead of finding out if this is a hard limit or not and if it can be extended, I decided to stick with 256.

**Comment by licoffe** [comment]
Reverting it back to 256 and closing the issue.
